language: cpp

script:
  - ./extract_input_info.sh
  - ./extract_output_info.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ctest -V; fi

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - gengetopt
            - gnuplot
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - gengetopt
            - gnuplot
